language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
install:
- npm install
deploy:
  provider: npm
  email: michaelandrewfischer@gmail.com
  api_key:
    secure: k+vNh1wgaFovAv05jwWr11T3AA5Xg0ehYonIwpDidq4IHQ85buhGSESZtJy0/IpFkN7Klx0b/LRWGU2mp3VOy22QuslhqtmYrvB9n39uZpOHbTe/ibmSr2KD6YdDfDdsS++OuoRJYJx4wsCm0YCsZj0RmxppuZ9+H928MINR2TKH2iOiHKeuy1ffkoRd8k8wOzqTPM7wSc7LTYSMJE8XmmERmpOh6SmmcUyEvmvH6qHrNkeqqwsbaODT3eakk/x9iiZPhLFVfdWBIGkQMynmQbEZY0N3U+e9EKwwaa58VSrZVt4kSaMIYleiYkdO8+0M+Sc51w7ED1WxvM2eeTCOMHIjR2y9vNEuXj5w5B7ejYgr9IF6v4iBxOk4GwPLAFdKzU20JlbJf1HDVeWVqA8jdno9c6uUGUKmfQDZ/33D8Qv1r5me3GQwaLTRwD7IyWbFr0ykYVBnYef1VtwlYKw2B5+n+3Kx92FGZcz5vDwZ7XO9G+QarJEePVNw6KBKRO7mdtPSmT602yh2aP6ZSGiIrfhMNDzmiV9PzFJ24dSJiu3yszLuK6KNYfTNyM6FEcwCn3APxkt1w407XbXO5/Vm/r+6E89ffNokPdHM79Zy2us8UL1w83qJQj4gYo/hvoLjyOdcV3AMKHFq7af0BIDQEE9le44LBzx8t0PvNEElW7w=
  on:
    tags: true
    repo: mafischer/raml-api-tester
    branch: master
